# Generated by Django 5.1 on 2025-01-12 08:41

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_task', '0001_initial'),
        ('contacts', '0002_contactitem_delete_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=25)),
                ('color', models.CharField(max_length=25)),
                ('categoryType', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=25)),
                ('due_date', models.DateField()),
                ('priorityValue', models.CharField(max_length=10)),
                ('statusCategory', models.CharField(max_length=25)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubtaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtaskName', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=6)),
                ('parent_task_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='add_task.taskitem')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedContactItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contacts.contactitem')),
                ('parent_task_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='add_task.taskitem')),
            ],
        ),
        migrations.DeleteModel(
            name='task',
        ),
    ]
