# Generated by Django 5.0.7 on 2024-08-08 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_task', '0003_rename_assigned_contact_id_assignedcontactitem_user_id'),
        ('contacts', '0005_contactitem_active_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedcontactitem',
            name='contactColor',
        ),
        migrations.RemoveField(
            model_name='assignedcontactitem',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='assignedcontactitem',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='assignedcontactitem',
            name='user_id',
        ),
        migrations.AddField(
            model_name='assignedcontactitem',
            name='contact_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contacts.contactitem'),
        ),
    ]
