# Generated by Django 5.1 on 2025-01-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contactitem_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactitem',
            name='text_color',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
