# Generated by Django 5.0.7 on 2024-08-05 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_contact_created_by_alter_contact_color_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='ContactItem',
        ),
    ]
