# Generated by Django 5.0.7 on 2024-08-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_rename_contact_contactitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactitem',
            name='phone',
            field=models.CharField(max_length=25),
        ),
    ]
